### ISSUE TITLE
@semantic-release/gitlab support

### ISSUE THREAD

**Issue by wallacer** [TheUnderScorer/nx-semantic-release#76] opened 2023-08-24 17:28 UTC
Feature request for Gitlab support via [`@semantic-release/gitlab`](https://github.com/semantic-release/gitlab)

**Comment by mat813** [comment] 2023-09-15 13:54
I tried adding this to the nxrelease block:

```json
    "plugins": [
      "@semantic-release/gitlab"
    ]
```

but I get this error:


```
[1:42:24 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[1:42:24 PM] [semantic-release] › ✘  Failed step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[1:42:24 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/components/node_modules/@semantic-release/gitlab/index.js from /builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at nx-semantic-release (/builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///builds/components/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: nx-semantic-release]'
}
 >  NX   require() of ES Module /builds/components/node_modules/@semantic-release/gitlab/index.js from /builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
   Instead change the require of index.js in /builds/components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
   Pass --verbose to see the stacktrace.
```

and it goes a bit beyond what I understand 😢

**Comment by TheUnderScorer** [comment] 2023-09-18 08:17
@mat813 did you manage to get it working on the `9.5.1` version?

**Comment by mat813** [comment] 2023-09-18 08:36
Yes, I added what I pasted above, and it was enough. That and setting github to false.

**Comment by TheUnderScorer** [comment] 2023-09-18 10:11
Thanks! I will mention that in the readme.

Seems like the issue is solved, so I'll close it.

**Closed by TheUnderScorer** 2023-09-18 10:11 UTC
Labels: enhancement, good first issue
